s2_module_module:
    resource: "@S2ModuleBundle/Resources/config/routing/module.yml"
    prefix:   /module

s2_module_homepage:
    path:     /demo-video/{name}
    defaults: { _controller: S2ModuleBundle:Default:index }

s2_module_annotations:
  resource: "@S2ModuleBundle/Controller"
  type: annotation