S2\PageBundle\Entity\InfoPage:
    type: entity
    table: null
    repositoryClass: S2\PageBundle\Entity\InfoPageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        image:
            type: string
            length: 255
        content:
            type: text
    lifecycleCallbacks: {  }
