<?php

namespace S2\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoPageRepository extends EntityRepository
{
}
